rules:
  - id: account-age-min
    enabled: true
    minAccountAgeDays: 100000
  - id: user-public-repos-min
    enabled: true
    minPublicRepos: 500
  - id: pr-total-changes-min
    enabled: true
    minTotalChanges: 500000
